// Dados de fallback anonimizados — exibidos quando a API do N8N está offline.
// NÃO contém dados reais de colaboradores.
export const FALLBACK_DATA = [
  { asset_tag:"001",hostname_esperado:"PC-001",serial:"EXEMPLO001",modelo:"Modelo A",fabricante:"Fabricante X",categoria:"Desktop",colaborador:"Usuário 01",colaborador_email:"usuario01@empresa.com",localizacao:"T.I",status_snipe:"Ativo",status_limpeza:"NUNCA",status_limpeza_label:"Nunca executado",ultima_execucao_em:null,ultimo_status_geral:null,ultimo_status_msg:null,total_etapas:null,ok_count:null,aviso_count:null,erro_count:null,usuario_execucao:null,dias_desde_ultima_limpeza:null,saude_limpeza:"CRITICO" },
  { asset_tag:"002",hostname_esperado:"PC-002",serial:"EXEMPLO002",modelo:"Modelo B",fabricante:"Fabricante Y",categoria:"Notebook",colaborador:"Usuário 02",colaborador_email:"usuario02@empresa.com",localizacao:"T.I",status_snipe:"Ativo",status_limpeza:"NUNCA",status_limpeza_label:"Nunca executado",ultima_execucao_em:null,ultimo_status_geral:null,ultimo_status_msg:null,total_etapas:null,ok_count:null,aviso_count:null,erro_count:null,usuario_execucao:null,dias_desde_ultima_limpeza:null,saude_limpeza:"CRITICO" },
  { asset_tag:"003",hostname_esperado:"PC-003",serial:"EXEMPLO003",modelo:"Modelo C",fabricante:"Fabricante Z",categoria:"Notebook",colaborador:"Usuário 03",colaborador_email:"usuario03@empresa.com",localizacao:"Operações",status_snipe:"Ativo",status_limpeza:"AVISO",status_limpeza_label:"Concluído com avisos",ultima_execucao_em:"27/02/2026 14:46",ultimo_status_geral:"AVISO",ultimo_status_msg:"2 avisos, 22/20 etapas concluídas sem erro",total_etapas:20,ok_count:22,aviso_count:2,erro_count:0,usuario_execucao:"PC-003",dias_desde_ultima_limpeza:3,saude_limpeza:"EM_DIA" },
  { asset_tag:"004",hostname_esperado:"PC-004",serial:"EXEMPLO004",modelo:"Modelo A",fabricante:"Fabricante X",categoria:"All in one",colaborador:"Usuário 04",colaborador_email:"usuario04@empresa.com",localizacao:"Comercial",status_snipe:"Ativo",status_limpeza:"NUNCA",status_limpeza_label:"Nunca executado",ultima_execucao_em:null,ultimo_status_geral:null,ultimo_status_msg:null,total_etapas:null,ok_count:null,aviso_count:null,erro_count:null,usuario_execucao:null,dias_desde_ultima_limpeza:null,saude_limpeza:"CRITICO" },
  { asset_tag:"005",hostname_esperado:"PC-005",serial:"EXEMPLO005",modelo:"Modelo D",fabricante:"Fabricante W",categoria:"Notebook",colaborador:"Usuário 05",colaborador_email:"usuario05@empresa.com",localizacao:"Financeiro",status_snipe:"Ativo",status_limpeza:"NUNCA",status_limpeza_label:"Nunca executado",ultima_execucao_em:null,ultimo_status_geral:null,ultimo_status_msg:null,total_etapas:null,ok_count:null,aviso_count:null,erro_count:null,usuario_execucao:null,dias_desde_ultima_limpeza:null,saude_limpeza:"CRITICO" },
  { asset_tag:"006",hostname_esperado:"PC-006",serial:"EXEMPLO006",modelo:"Modelo B",fabricante:"Fabricante Y",categoria:"Notebook",colaborador:"Usuário 06",colaborador_email:"usuario06@empresa.com",localizacao:"RH",status_snipe:"Ativo",status_limpeza:"NUNCA",status_limpeza_label:"Nunca executado",ultima_execucao_em:null,ultimo_status_geral:null,ultimo_status_msg:null,total_etapas:null,ok_count:null,aviso_count:null,erro_count:null,usuario_execucao:null,dias_desde_ultima_limpeza:null,saude_limpeza:"CRITICO" },
  { asset_tag:"007",hostname_esperado:"PC-007",serial:"EXEMPLO007",modelo:"Modelo A",fabricante:"Fabricante X",categoria:"All in one",colaborador:"Usuário 07",colaborador_email:"usuario07@empresa.com",localizacao:"Operações",status_snipe:"Ativo",status_limpeza:"AVISO",status_limpeza_label:"Concluído com avisos",ultima_execucao_em:"27/02/2026 14:50",ultimo_status_geral:"AVISO",ultimo_status_msg:"2 avisos, 23/20 etapas concluídas sem erro",total_etapas:20,ok_count:23,aviso_count:2,erro_count:0,usuario_execucao:"PC-007",dias_desde_ultima_limpeza:3,saude_limpeza:"EM_DIA" },
];
